version: "3.2"
services:
  ## web服务端
  web:
    container_name: "web"
    build:
      context: https://gitee.com/ddtechs/docker-php.git
      args:
        - PHP_VERSION=7.3
    ports:
      - 8081:80
    volumes:
      - ./../../:/app:delegated
      - ./config/apache.conf:/etc/apache2/sites-available/000-default.conf:delegated
  ## queue+socket服务端
  node:
    container_name: "node"
    build:
      context: https://gitee.com/ddtechs/docker-nodejs.git
      args:
        - NODE_VERSION=latest
    command:
      - /bin/sh
      - -c
      - |
        yarn upgrade --no-bin-links
        pm2 start example/web/socket.js --watch
        pm2 start example/web/queue.js --watch
        pm2 start example/web/client.js --watch
        pm2 save
        tail -f /dev/null
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: dev
    ports:
      - 3314:3314
      - 3315:3315
    volumes:
      - ./../../:/app:delegated
  ## Redis服务
  redis:
    container_name: "redis"
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]